package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.Stage;

import java.io.File;
import java.io.IOException;
import java.util.Random;

import javafx.event.ActionEvent;

public class MainSceneController {
	
	ImageView myImageView;
	private Button play;
	private Button accueil;
	private Button quit;
	private Button regles;
	private Button partie;
	private Button ordre;
	private Boolean valeur=false;
	Random random = new Random();

    @FXML
    private ImageView diceImage;

    @FXML
    private Button rollButton;
	// Event Listener on Button.onAction
	@FXML
	public void btPlay() {
		System.out.println("yes!");
		Stage stage= (Stage)play.getScene().getWindow();
		stage.close();
		Stage primaryStage = new Stage();
		try {
			System.out.println("no!");
			Parent root = FXMLLoader.load(getClass().getResource("beginOrdi.fxml"));
			primaryStage.setTitle("421");
			primaryStage.setScene( new Scene(root));
			primaryStage.show();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void btRegle() {
	}
	// Event Listener on CheckBox.onAction
	@FXML
	public void btOrdinateur(ActionEvent event) {
		// TODO Autogenerated
	}
	public void btAccueil(ActionEvent event) {
		// TODO Autogenerated
	}
	public void btQuit(ActionEvent event) {
		// TODO Autogenerated
	}
	public void btPartie(ActionEvent event) {
		// TODO Autogenerated
	}
	public void btOrdre(ActionEvent event) {
		// TODO Autogenerated
	}
	
	void roll(ActionEvent event) {

        rollButton.setDisable(true);

        Thread thread = new Thread(){
            public void run(){
                System.out.println("Thread Running");
                try {
                    for (int i = 0; i < 15; i++) {
                        File file = new File("src/dice/dice" + (random.nextInt(6)+1)+".png");
                        diceImage.setImage(new Image(file.toURI().toString()));
                        Thread.sleep(50);
                    }
                    rollButton.setDisable(false);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };

        thread.start();
    }
}
